#!/usr/bin/env python3
from __future__ import annotations
from pathlib import Path
import argparse, shutil
from common import ROOT, WORK, DIST, BuildError, write_json, require
from extensions_index import build_extension_index

INDEX = """<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no">
  <meta http-equiv="Content-Security-Policy" content="default-src 'self'; base-uri 'self'; object-src 'none'; script-src 'self' blob:; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data: blob:; connect-src 'self'; worker-src 'self' blob:; child-src 'self' blob:; frame-src 'self';">
  <meta id="vscode-workbench-web-configuration" data-settings="{}">
  <meta id="vscode-workbench-web-base-url" data-settings=".">
  <meta id="vscode-workbench-auth-session" data-settings="">
  <link rel="icon" href="./favicon.ico" type="image/x-icon">
  <link rel="manifest" href="./manifest.json">
  <link rel="stylesheet" href="./out/vs/code/browser/workbench/workbench.css">
  <title>Code OSS Static Web</title>
</head>
<body aria-label=""></body>
<script type="module" src="./static-bootstrap.mjs"></script>
</html>
"""

BOOTSTRAP = r"""// Generated by code-oss-static-web. External startup logic permits a strict static CSP.
const baseUrl = new URL('./', import.meta.url);
const runtime = await fetch(new URL('runtime.json', baseUrl), { cache: 'no-store' }).then(r => {
  if (!r.ok) throw new Error(`runtime.json: ${r.status}`);
  return r.json();
});
const extensionIndex = await fetch(new URL('extensions.json', baseUrl), { cache: 'no-store' }).then(r => {
  if (!r.ok) throw new Error(`extensions.json: ${r.status}`);
  return r.json();
});

function browserUri(relativePath) {
  const u = new URL(relativePath, baseUrl);
  return { scheme: u.protocol.slice(0, -1), authority: u.host, path: u.pathname };
}

const additionalBuiltinExtensions = extensionIndex.extensions
  .filter(ext => ext.browserCompatible)
  .map(ext => browserUri(ext.path));

const config = {
  workspaceUri: runtime.workspace ?? { scheme: 'tmp', path: '/default.code-workspace' },
  callbackRoute: new URL('callback.html', baseUrl).pathname,
  enableWorkspaceTrust: true,
  additionalBuiltinExtensions,
  productConfiguration: {
    enableTelemetry: runtime.telemetry === true,
    webEndpointUrlTemplate: 'https://{{uuid}}.invalid.invalid',
    webviewContentExternalBaseUrlTemplate: 'https://{{uuid}}.invalid.invalid/out/vs/workbench/contrib/webview/browser/pre/',
    voiceWsUrl: ''
  }
};

document.getElementById('vscode-workbench-web-configuration')
  .setAttribute('data-settings', JSON.stringify(config));
document.getElementById('vscode-workbench-web-base-url')
  .setAttribute('data-settings', baseUrl.href.replace(/\/$/, ''));
globalThis._VSCODE_FILE_ROOT = new URL('out/', baseUrl).href;
performance.mark('code/willLoadWorkbenchMain');
await import(new URL('out/nls.messages.js', baseUrl).href);
await import(new URL('out/vs/code/browser/workbench/workbench.js', baseUrl).href);
"""

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--input', type=Path, default=WORK / 'vscode-web')
    ap.add_argument('--output', type=Path, default=DIST)
    ns = ap.parse_args()
    src, out = ns.input.resolve(), ns.output.resolve()
    require((src / 'out/vs/code/browser/workbench/workbench.js').is_file(), f'not a VS Code web build: {src}')
    if out.exists():
        shutil.rmtree(out)
    shutil.copytree(src, out, symlinks=True)
    shutil.copy2(ROOT / 'config/runtime.json', out / 'runtime.json')
    (out / 'index.html').write_text(INDEX, encoding='utf-8')
    (out / 'static-bootstrap.mjs').write_text(BOOTSTRAP, encoding='utf-8')
    write_json(out / 'extensions.json', build_extension_index(out))
    upstream = WORK / 'vscode'
    for source, target in [
        (upstream / 'LICENSE.txt', out / 'LICENSE.Code-OSS.txt'),
        (upstream / 'ThirdPartyNotices.txt', out / 'ThirdPartyNotices.Code-OSS.txt'),
    ]:
        if source.exists():
            shutil.copy2(source, target)
    callback = out / 'out/vs/code/browser/workbench/callback.html'
    if callback.exists():
        shutil.copy2(callback, out / 'callback.html')
    else:
        (out / 'callback.html').write_text('<!doctype html><meta charset="utf-8"><title>Callback unavailable</title>', encoding='utf-8')
    print(f'static distribution: {out}')

if __name__ == '__main__':
    try:
        main()
    except BuildError as e:
        raise SystemExit(str(e))
