#!/usr/bin/env python3
from __future__ import annotations

import argparse
import html
import json
import shutil
from pathlib import Path

from common import DIST, WORK, BuildError, require, write_json
from deployment_profile import load_selected_profile, profile_metadata
from extension_lock import install_locked_extensions
from extensions_index import build_extension_index

WORKBENCH_ENTRY = 'out/vs/workbench/workbench.web.main.internal.js'
WORKBENCH_STYLESHEET = 'out/vs/workbench/workbench.web.main.internal.css'

INDEX = """<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no">
  <meta http-equiv="Content-Security-Policy" content="default-src 'self'; base-uri 'self'; object-src 'none'; script-src 'self' blob:; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data: blob:; connect-src 'self'; worker-src 'self' blob:; child-src 'self' blob:; frame-src 'self';">
  <meta id="vscode-workbench-web-configuration" data-settings="{}">
  <link rel="icon" href="./favicon.ico" type="image/x-icon">
  <link rel="manifest" href="./manifest.json">
  <link rel="stylesheet" href="./out/vs/workbench/workbench.web.main.internal.css">
  <title>Code OSS Static Web</title>
</head>
<body aria-label=""></body>
<script type="module" src="./static-bootstrap.mjs"></script>
</html>
"""


def build_index(title: str, network: dict[str, object]) -> str:
    require(network.get('default') == 'deny', 'network policy must default deny')
    require(network.get('allowedOrigins') == ['self'], 'network policy must allow self only')
    require(bool(title), 'branding title must be non-empty')
    safe_title = html.escape(title, quote=False)
    return INDEX.replace('<title>Code OSS Static Web</title>', f'<title>{safe_title}</title>')


BOOTSTRAP = r"""// Generated by code-oss-static-web. External startup logic permits a strict static CSP.
const baseUrl = new URL('./', import.meta.url);
const runtime = await fetch(new URL('runtime.json', baseUrl), { cache: 'no-store' }).then(r => {
  if (!r.ok) throw new Error(`runtime.json: ${r.status}`);
  return r.json();
});
const additionalExtensionIndex = await fetch(
  new URL('additional-extensions.json', baseUrl),
  { cache: 'no-store' }
).then(r => {
  if (!r.ok) throw new Error(`additional-extensions.json: ${r.status}`);
  return r.json();
});

function browserUri(relativePath) {
  const u = new URL(relativePath, baseUrl);
  return { scheme: u.protocol.slice(0, -1), authority: u.host, path: u.pathname };
}

const additionalBuiltinExtensions = additionalExtensionIndex.extensions
  .map(ext => browserUri(ext.path));

const config = {
  enableWorkspaceTrust: true,
  additionalBuiltinExtensions,
  configurationDefaults: {
    'workbench.startupEditor': 'none'
  },
  productConfiguration: {
    enableTelemetry: runtime.telemetry === true,
    webEndpointUrlTemplate: 'https://{{uuid}}.invalid.invalid',
    webviewContentExternalBaseUrlTemplate: 'https://{{uuid}}.invalid.invalid/out/vs/workbench/contrib/webview/browser/pre/',
    voiceWsUrl: ''
  }
};

document.getElementById('vscode-workbench-web-configuration')
  .setAttribute('data-settings', JSON.stringify(config));
globalThis._VSCODE_FILE_ROOT = new URL('out/', baseUrl).href;
performance.mark('code/willLoadWorkbenchMain');
await import(new URL('out/nls.messages.js', baseUrl).href);
const { create } = await import(
  new URL('out/vs/workbench/workbench.web.main.internal.js', baseUrl).href
);
create(document.body, config);
"""


def build_bootstrap(webview: dict[str, object]) -> str:
    require(webview.get('mode') == 'disabled', 'unsupported webview mode')
    template = webview.get('externalBaseUrlTemplate')
    require(
        isinstance(template, str) and 'invalid.invalid' in template,
        'webview template must fail closed',
    )
    return BOOTSTRAP.replace(
        "'https://{{uuid}}.invalid.invalid/out/vs/workbench/contrib/webview/browser/pre/'",
        json.dumps(template),
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument('--input', type=Path, default=WORK / 'vscode-web')
    parser.add_argument('--output', type=Path, default=DIST)
    args = parser.parse_args()

    source = args.input.resolve()
    output = args.output.resolve()
    require((source / WORKBENCH_ENTRY).is_file(), f'not a standalone Code OSS web build: {source}')
    require(
        (source / WORKBENCH_STYLESHEET).is_file(),
        f'standalone Code OSS web stylesheet missing: {source}',
    )

    profile = load_selected_profile()
    branding = profile['documents']['branding']
    network = profile['documents']['network']
    webview = profile['documents']['webview']

    if output.exists():
        shutil.rmtree(output)
    shutil.copytree(source, output, symlinks=True)
    shutil.copy2(profile['paths']['runtime'], output / 'runtime.json')
    write_json(output / 'deployment-profile.json', profile_metadata(profile))
    (output / 'index.html').write_text(
        build_index(branding['title'], network),
        encoding='utf-8',
    )
    (output / 'static-bootstrap.mjs').write_text(
        build_bootstrap(webview),
        encoding='utf-8',
    )

    installed = install_locked_extensions(
        output,
        profile['paths']['extensionLock'],
        license_policy_path=profile['paths']['extensionLicensePolicy'],
        source_policy_path=profile['paths']['extensionSourcePolicy'],
    )
    write_json(
        output / 'locked-extensions.json',
        {'schemaVersion': 1, 'extensions': installed},
    )
    write_json(
        output / 'additional-extensions.json',
        {
            'schemaVersion': 1,
            'extensions': [
                {
                    'id': extension['id'],
                    'path': f'extensions/{extension["id"]}/',
                }
                for extension in installed
            ],
        },
    )
    write_json(output / 'extensions.json', build_extension_index(output))

    upstream = WORK / 'vscode'
    for source_file, target_file in [
        (upstream / 'LICENSE.txt', output / 'LICENSE.Code-OSS.txt'),
        (upstream / 'ThirdPartyNotices.txt', output / 'ThirdPartyNotices.Code-OSS.txt'),
    ]:
        if source_file.exists():
            shutil.copy2(source_file, target_file)

    callback = output / 'out/vs/code/browser/workbench/callback.html'
    if callback.exists():
        shutil.copy2(callback, output / 'callback.html')
    else:
        (output / 'callback.html').write_text(
            '<!doctype html><meta charset="utf-8"><title>Callback unavailable</title>',
            encoding='utf-8',
        )

    print(f'static distribution: {output}')


if __name__ == '__main__':
    try:
        main()
    except BuildError as exc:
        raise SystemExit(str(exc)) from None
