#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
from pathlib import Path

from common import BuildError, require, write_json

SLUG_RE = re.compile(r'^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$')

ROLE_KEYS = ('platform', 'security', 'release', 'extensionPolicy', 'legal')


def validate_slug(value: str, label: str) -> None:
    require(SLUG_RE.fullmatch(value) is not None, f'invalid {label} slug: {value!r}')


def mapping(organization: str, teams: dict[str, str]) -> dict[str, object]:
    validate_slug(organization, 'organization')
    require(set(teams) == set(ROLE_KEYS), 'governance team roles invalid')
    for role, slug in teams.items():
        validate_slug(slug, role)
    require(len(set(teams.values())) == len(teams), 'governance roles must use distinct team slugs')
    return {
        'schemaVersion': 1,
        'organization': organization,
        'teams': teams,
    }


def team_owner(config: dict[str, object], role: str) -> str:
    organization = config['organization']
    teams = config['teams']
    assert isinstance(organization, str)
    assert isinstance(teams, dict)
    slug = teams[role]
    assert isinstance(slug, str)
    return f'@{organization}/{slug}'


def render_codeowners(config: dict[str, object]) -> str:
    owners = {role: team_owner(config, role) for role in ROLE_KEYS}
    rows = [
        ('/.github/', ('platform', 'security')),
        ('/GOVERNANCE.md', ('platform', 'security')),
        ('/CONTRIBUTING.md', ('platform', 'security')),
        ('/SECURITY.md', ('security',)),
        ('/OPERATIONS.md', ('release', 'platform')),
        ('/renovate.json', ('platform', 'security')),
        ('/security/', ('security',)),
        ('/extensions/', ('extensionPolicy', 'platform', 'security')),
        ('/extensions/license-policy.json', ('legal', 'extensionPolicy')),
        ('/extensions/source-policy.json', ('extensionPolicy', 'security')),
        ('/deploy/', ('release', 'platform')),
        ('/scripts/', ('platform', 'security')),
        ('/config/', ('platform', 'security')),
        ('/patches/', ('platform', 'security')),
        ('/build.sh', ('platform', 'security')),
        ('/package.sh', ('platform', 'security')),
        ('/docs/release-security.md', ('security', 'release')),
        ('/docs/releasing.md', ('release', 'platform')),
        ('/docs/organization-migration.md', ('platform', 'security', 'release')),
    ]
    lines = [
        '# Organization team-backed sensitive-path ownership.',
        '# Generated by scripts/render_codeowners.py from .github/governance-teams.json.',
        '# upstream.lock.json intentionally remains outside CODEOWNERS for the zero-touch upstream path.',
        '',
    ]
    for pattern, roles in rows:
        lines.append(pattern + ' ' + ' '.join(owners[role] for role in roles))
    return '\n'.join(lines) + '\n'


def main() -> None:
    parser = argparse.ArgumentParser(description='Render organization-team CODEOWNERS policy')
    parser.add_argument('--organization', required=True)
    parser.add_argument('--platform-team', required=True)
    parser.add_argument('--security-team', required=True)
    parser.add_argument('--release-team', required=True)
    parser.add_argument('--extension-policy-team', required=True)
    parser.add_argument('--legal-team', required=True)
    parser.add_argument('--codeowners', type=Path, default=Path('.github/CODEOWNERS'))
    parser.add_argument('--mapping', type=Path, default=Path('.github/governance-teams.json'))
    args = parser.parse_args()

    config = mapping(
        args.organization,
        {
            'platform': args.platform_team,
            'security': args.security_team,
            'release': args.release_team,
            'extensionPolicy': args.extension_policy_team,
            'legal': args.legal_team,
        },
    )
    args.codeowners.write_text(render_codeowners(config), encoding='utf-8')
    write_json(args.mapping, config)
    print(f'organization CODEOWNERS: {args.codeowners}')


if __name__ == '__main__':
    try:
        main()
    except BuildError as exc:
        raise SystemExit(str(exc)) from None
